"""Regenerate docs/catalogue.json and docs/gallery.md from the current code.

Run::

    poetry run python scripts/build_catalogue.py

Re-run whenever style / recipe docstrings change, or when adding new styles.
The generated files are checked into the repo as the canonical agent-facing index.
"""

from __future__ import annotations

from pathlib import Path

from motor_graphs.catalogue import build_catalogue, write_catalogue

REPO = Path(__file__).parent.parent
DOCS = REPO / "docs"
BASELINES = REPO / "tests" / "baselines"
CATALOGUE_JSON = DOCS / "catalogue.json"
GALLERY_MD = DOCS / "gallery.md"


def _summarise_params(entry: dict) -> str:
    """Return a one-line signature summary like 'df, *, cohort="cohort", n="n"'."""
    parts = []
    saw_star = False
    for p in entry["parameters"]:
        if p["kind"] == "KEYWORD_ONLY" and not saw_star:
            parts.append("*")
            saw_star = True
        if p["has_default"]:
            default = p["default"]
            if isinstance(default, str) and not default.startswith(("[", "{", "(")):
                default_repr = f'"{default}"'
            else:
                default_repr = repr(default)
            parts.append(f'{p["name"]}={default_repr}')
        else:
            parts.append(p["name"])
    return ", ".join(parts)


def _render_gallery(catalogue: dict) -> str:
    lines = []
    lines.append("# motor-graph-generation gallery — v0.1\n")
    lines.append(
        f"_Auto-generated by `scripts/build_catalogue.py`. {catalogue['n_styles']} "
        f"chart styles + {catalogue['n_recipes']} recipes._\n"
    )
    lines.append(
        "**Don't edit this file by hand** — change the underlying docstrings then re-run "
        "`poetry run python scripts/build_catalogue.py`.\n"
    )

    # --- Styles section ---
    lines.append("## Chart styles\n")
    lines.append(
        "Plotly chart-style primitives. Each takes a tidy `pandas.DataFrame` and "
        "returns a `plotly.graph_objects.Figure`. Source: `motor_graphs.styles`.\n"
    )
    for entry in catalogue["styles"]:
        baseline_rel = f"../tests/baselines/{entry['name']}.png"
        lines.append(f"### `{entry['name']}`\n")
        if entry["summary"]:
            lines.append(f"{entry['summary']}\n")
        if (BASELINES / f"{entry['name']}.png").exists():
            lines.append(f"![{entry['name']}]({baseline_rel})\n")
        if entry["use_when"]:
            lines.append(f"**Use this when:**\n\n{entry['use_when']}\n")
        if entry["data_shape"]:
            lines.append("**Data shape:**\n\n```\n" + entry["data_shape"] + "\n```\n")
        lines.append(
            f"**Signature:** `{entry['name']}({_summarise_params(entry)}) -> go.Figure`\n"
        )
        lines.append(f"_Module:_ `{entry['module']}`\n")
        lines.append("---\n")

    # --- Recipes section ---
    lines.append("## Recipes (Snowflake-aware)\n")
    lines.append(
        "Thin wrappers that load real PROD data via `motor_graphs.data.snowflake` "
        "and call one of the styles above. Source: `motor_graphs.recipes`. "
        "Every recipe takes `(cohort_start, cohort_end)` as its first two arguments "
        "(date | str).\n"
    )
    for entry in catalogue["recipes"]:
        lines.append(f"### `{entry['name']}`\n")
        if entry["summary"]:
            lines.append(f"{entry['summary']}\n")
        if entry["use_when"]:
            lines.append(f"**Use this when:**\n\n{entry['use_when']}\n")
        if entry["snowflake_tables_used"]:
            lines.append(
                "**Snowflake tables used:**\n\n"
                + entry["snowflake_tables_used"]
                + "\n"
            )
        lines.append(
            f"**Signature:** `{entry['name']}({_summarise_params(entry)}) -> go.Figure`\n"
        )
        lines.append(f"_Module:_ `{entry['module']}`\n")
        lines.append("---\n")

    return "\n".join(lines) + "\n"


def main() -> None:
    DOCS.mkdir(parents=True, exist_ok=True)
    print(f"Building catalogue (v{__import__('motor_graphs').__version__}) ...")
    catalogue = build_catalogue()
    write_catalogue(CATALOGUE_JSON)
    print(f"  ✓ wrote {CATALOGUE_JSON.relative_to(REPO)}")
    GALLERY_MD.write_text(_render_gallery(catalogue))
    print(f"  ✓ wrote {GALLERY_MD.relative_to(REPO)}")
    print(
        f"  → {catalogue['n_styles']} styles, {catalogue['n_recipes']} recipes "
        "documented."
    )


if __name__ == "__main__":
    main()
